#pragma once

// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tool/generate_force_link_symbols.sh.

#ifdef __cplusplus
extern "C" {
#endif

void isar_plus_force_link_all_symbols(void);

#ifdef __cplusplus
}
#endif
