#include <stddef.h>
#include "include/binding.h"

// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by tool/generate_force_link_symbols.sh from Dart FFI bindings.
// Force the linker to pull all Isar Plus FFI entry points from the static archive.
extern void isar_plus_auto_increment(void);
extern void isar_plus_buffer_free(void);
extern void isar_plus_clear(void);
extern void isar_plus_close(void);
extern void isar_plus_connect_dart_api(void);
extern void isar_plus_copy(void);
extern void isar_plus_count(void);
extern void isar_plus_cursor(void);
extern void isar_plus_cursor_free(void);
extern void isar_plus_cursor_next(void);
extern void isar_plus_delete(void);
extern void isar_plus_delete_database(void);
extern void isar_plus_filter_and(void);
extern void isar_plus_filter_between(void);
extern void isar_plus_filter_equal(void);
extern void isar_plus_filter_greater(void);
extern void isar_plus_filter_greater_or_equal(void);
extern void isar_plus_filter_is_null(void);
extern void isar_plus_filter_less(void);
extern void isar_plus_filter_less_or_equal(void);
extern void isar_plus_filter_nested(void);
extern void isar_plus_filter_not(void);
extern void isar_plus_filter_or(void);
extern void isar_plus_filter_string_contains(void);
extern void isar_plus_filter_string_ends_with(void);
extern void isar_plus_filter_string_matches(void);
extern void isar_plus_filter_string_starts_with(void);
extern void isar_plus_get_dir(void);
extern void isar_plus_get_error(void);
extern void isar_plus_get_instance(void);
extern void isar_plus_get_name(void);
extern void isar_plus_get_size(void);
extern void isar_plus_import_json(void);
extern void isar_plus_insert(void);
extern void isar_plus_insert_abort(void);
extern void isar_plus_insert_finish(void);
extern void isar_plus_insert_save(void);
extern void isar_plus_open_instance(void);
extern void isar_plus_query_add_distinct(void);
extern void isar_plus_query_add_sort(void);
extern void isar_plus_query_aggregate(void);
extern void isar_plus_query_build(void);
extern void isar_plus_query_cursor(void);
extern void isar_plus_query_cursor_free(void);
extern void isar_plus_query_cursor_next(void);
extern void isar_plus_query_delete(void);
extern void isar_plus_query_free(void);
extern void isar_plus_query_new(void);
extern void isar_plus_query_set_filter(void);
extern void isar_plus_query_update(void);
extern void isar_plus_read_bool(void);
extern void isar_plus_read_byte(void);
extern void isar_plus_read_double(void);
extern void isar_plus_read_float(void);
extern void isar_plus_read_free(void);
extern void isar_plus_read_id(void);
extern void isar_plus_read_int(void);
extern void isar_plus_read_list(void);
extern void isar_plus_read_long(void);
extern void isar_plus_read_null(void);
extern void isar_plus_read_object(void);
extern void isar_plus_read_string(void);
extern void isar_plus_read_to_json(void);
extern void isar_plus_stop_watching(void);
extern void isar_plus_string(void);
extern void isar_plus_string_free(void);
extern void isar_plus_txn_abort(void);
extern void isar_plus_txn_begin(void);
extern void isar_plus_txn_commit(void);
extern void isar_plus_update(void);
extern void isar_plus_update_add_value(void);
extern void isar_plus_update_new(void);
extern void isar_plus_value_bool(void);
extern void isar_plus_value_free(void);
extern void isar_plus_value_get_bool(void);
extern void isar_plus_value_get_integer(void);
extern void isar_plus_value_get_real(void);
extern void isar_plus_value_get_string(void);
extern void isar_plus_value_integer(void);
extern void isar_plus_value_real(void);
extern void isar_plus_value_string(void);
extern void isar_plus_verify(void);
extern void isar_plus_version(void);
extern void isar_plus_watch_collection(void);
extern void isar_plus_watch_collection_detailed(void);
extern void isar_plus_watch_object(void);
extern void isar_plus_watch_query(void);
extern void isar_plus_web_persistence_backend(void);
extern void isar_plus_web_persistence_poll(void);
extern void isar_plus_web_persistence_start(void);
extern void isar_plus_write_bool(void);
extern void isar_plus_write_byte(void);
extern void isar_plus_write_byte_list(void);
extern void isar_plus_write_double(void);
extern void isar_plus_write_float(void);
extern void isar_plus_write_int(void);
extern void isar_plus_write_json(void);
extern void isar_plus_write_list(void);
extern void isar_plus_write_list_end(void);
extern void isar_plus_write_long(void);
extern void isar_plus_write_null(void);
extern void isar_plus_write_object(void);
extern void isar_plus_write_object_end(void);
extern void isar_plus_write_string(void);

typedef void (*IsarPlusForceLinkSymbol)(void);

__attribute__((used))
static const IsarPlusForceLinkSymbol isar_plus_force_link_symbols[] = {
    (IsarPlusForceLinkSymbol)&isar_plus_auto_increment,
    (IsarPlusForceLinkSymbol)&isar_plus_buffer_free,
    (IsarPlusForceLinkSymbol)&isar_plus_clear,
    (IsarPlusForceLinkSymbol)&isar_plus_close,
    (IsarPlusForceLinkSymbol)&isar_plus_connect_dart_api,
    (IsarPlusForceLinkSymbol)&isar_plus_copy,
    (IsarPlusForceLinkSymbol)&isar_plus_count,
    (IsarPlusForceLinkSymbol)&isar_plus_cursor,
    (IsarPlusForceLinkSymbol)&isar_plus_cursor_free,
    (IsarPlusForceLinkSymbol)&isar_plus_cursor_next,
    (IsarPlusForceLinkSymbol)&isar_plus_delete,
    (IsarPlusForceLinkSymbol)&isar_plus_delete_database,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_and,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_between,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_equal,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_greater,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_greater_or_equal,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_is_null,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_less,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_less_or_equal,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_nested,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_not,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_or,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_string_contains,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_string_ends_with,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_string_matches,
    (IsarPlusForceLinkSymbol)&isar_plus_filter_string_starts_with,
    (IsarPlusForceLinkSymbol)&isar_plus_get_dir,
    (IsarPlusForceLinkSymbol)&isar_plus_get_error,
    (IsarPlusForceLinkSymbol)&isar_plus_get_instance,
    (IsarPlusForceLinkSymbol)&isar_plus_get_name,
    (IsarPlusForceLinkSymbol)&isar_plus_get_size,
    (IsarPlusForceLinkSymbol)&isar_plus_import_json,
    (IsarPlusForceLinkSymbol)&isar_plus_insert,
    (IsarPlusForceLinkSymbol)&isar_plus_insert_abort,
    (IsarPlusForceLinkSymbol)&isar_plus_insert_finish,
    (IsarPlusForceLinkSymbol)&isar_plus_insert_save,
    (IsarPlusForceLinkSymbol)&isar_plus_open_instance,
    (IsarPlusForceLinkSymbol)&isar_plus_query_add_distinct,
    (IsarPlusForceLinkSymbol)&isar_plus_query_add_sort,
    (IsarPlusForceLinkSymbol)&isar_plus_query_aggregate,
    (IsarPlusForceLinkSymbol)&isar_plus_query_build,
    (IsarPlusForceLinkSymbol)&isar_plus_query_cursor,
    (IsarPlusForceLinkSymbol)&isar_plus_query_cursor_free,
    (IsarPlusForceLinkSymbol)&isar_plus_query_cursor_next,
    (IsarPlusForceLinkSymbol)&isar_plus_query_delete,
    (IsarPlusForceLinkSymbol)&isar_plus_query_free,
    (IsarPlusForceLinkSymbol)&isar_plus_query_new,
    (IsarPlusForceLinkSymbol)&isar_plus_query_set_filter,
    (IsarPlusForceLinkSymbol)&isar_plus_query_update,
    (IsarPlusForceLinkSymbol)&isar_plus_read_bool,
    (IsarPlusForceLinkSymbol)&isar_plus_read_byte,
    (IsarPlusForceLinkSymbol)&isar_plus_read_double,
    (IsarPlusForceLinkSymbol)&isar_plus_read_float,
    (IsarPlusForceLinkSymbol)&isar_plus_read_free,
    (IsarPlusForceLinkSymbol)&isar_plus_read_id,
    (IsarPlusForceLinkSymbol)&isar_plus_read_int,
    (IsarPlusForceLinkSymbol)&isar_plus_read_list,
    (IsarPlusForceLinkSymbol)&isar_plus_read_long,
    (IsarPlusForceLinkSymbol)&isar_plus_read_null,
    (IsarPlusForceLinkSymbol)&isar_plus_read_object,
    (IsarPlusForceLinkSymbol)&isar_plus_read_string,
    (IsarPlusForceLinkSymbol)&isar_plus_read_to_json,
    (IsarPlusForceLinkSymbol)&isar_plus_stop_watching,
    (IsarPlusForceLinkSymbol)&isar_plus_string,
    (IsarPlusForceLinkSymbol)&isar_plus_string_free,
    (IsarPlusForceLinkSymbol)&isar_plus_txn_abort,
    (IsarPlusForceLinkSymbol)&isar_plus_txn_begin,
    (IsarPlusForceLinkSymbol)&isar_plus_txn_commit,
    (IsarPlusForceLinkSymbol)&isar_plus_update,
    (IsarPlusForceLinkSymbol)&isar_plus_update_add_value,
    (IsarPlusForceLinkSymbol)&isar_plus_update_new,
    (IsarPlusForceLinkSymbol)&isar_plus_value_bool,
    (IsarPlusForceLinkSymbol)&isar_plus_value_free,
    (IsarPlusForceLinkSymbol)&isar_plus_value_get_bool,
    (IsarPlusForceLinkSymbol)&isar_plus_value_get_integer,
    (IsarPlusForceLinkSymbol)&isar_plus_value_get_real,
    (IsarPlusForceLinkSymbol)&isar_plus_value_get_string,
    (IsarPlusForceLinkSymbol)&isar_plus_value_integer,
    (IsarPlusForceLinkSymbol)&isar_plus_value_real,
    (IsarPlusForceLinkSymbol)&isar_plus_value_string,
    (IsarPlusForceLinkSymbol)&isar_plus_verify,
    (IsarPlusForceLinkSymbol)&isar_plus_version,
    (IsarPlusForceLinkSymbol)&isar_plus_watch_collection,
    (IsarPlusForceLinkSymbol)&isar_plus_watch_collection_detailed,
    (IsarPlusForceLinkSymbol)&isar_plus_watch_object,
    (IsarPlusForceLinkSymbol)&isar_plus_watch_query,
    (IsarPlusForceLinkSymbol)&isar_plus_web_persistence_backend,
    (IsarPlusForceLinkSymbol)&isar_plus_web_persistence_poll,
    (IsarPlusForceLinkSymbol)&isar_plus_web_persistence_start,
    (IsarPlusForceLinkSymbol)&isar_plus_write_bool,
    (IsarPlusForceLinkSymbol)&isar_plus_write_byte,
    (IsarPlusForceLinkSymbol)&isar_plus_write_byte_list,
    (IsarPlusForceLinkSymbol)&isar_plus_write_double,
    (IsarPlusForceLinkSymbol)&isar_plus_write_float,
    (IsarPlusForceLinkSymbol)&isar_plus_write_int,
    (IsarPlusForceLinkSymbol)&isar_plus_write_json,
    (IsarPlusForceLinkSymbol)&isar_plus_write_list,
    (IsarPlusForceLinkSymbol)&isar_plus_write_list_end,
    (IsarPlusForceLinkSymbol)&isar_plus_write_long,
    (IsarPlusForceLinkSymbol)&isar_plus_write_null,
    (IsarPlusForceLinkSymbol)&isar_plus_write_object,
    (IsarPlusForceLinkSymbol)&isar_plus_write_object_end,
    (IsarPlusForceLinkSymbol)&isar_plus_write_string,
};

__attribute__((used))
void isar_plus_force_link_all_symbols(void) {
    (void)isar_plus_force_link_symbols;
}
