#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)

BINDINGS_FILE="${BINDINGS_FILE:-$REPO_ROOT/packages/isar_plus/lib/src/native/bindings.dart}"
OUTPUT_FILE="${OUTPUT_FILE:-$REPO_ROOT/packages/isar_plus_flutter_libs/darwin/isar_plus_flutter_libs/Core/force_link_symbols.c}"
HEADER_FILE="${HEADER_FILE:-$REPO_ROOT/packages/isar_plus_flutter_libs/darwin/isar_plus_flutter_libs/Core/include/binding.h}"

symbols_file=$(mktemp)
tmp_output=$(mktemp)
tmp_header=$(mktemp)
cleanup() {
  rm -f "$symbols_file" "$tmp_output" "$tmp_header"
}
trap cleanup EXIT

if [[ -f "$BINDINGS_FILE" ]]; then
  if command -v rg >/dev/null 2>&1; then
    rg -o "'isar_plus_[A-Za-z0-9_]+'" "$BINDINGS_FILE" -S | tr -d "'" | sort -u > "$symbols_file" || true
  else
    grep -Eo "'isar_plus_[A-Za-z0-9_]+'" "$BINDINGS_FILE" | tr -d "'" | sort -u > "$symbols_file" || true
  fi
else
  echo "Bindings file not found, generating an empty force-link anchor: $BINDINGS_FILE" >&2
  : > "$symbols_file"
fi

{
  echo "#include <stddef.h>"
  echo "#include \"include/binding.h\""
  echo
  echo "// AUTO-GENERATED FILE. DO NOT EDIT."
  echo "// Generated by tool/generate_force_link_symbols.sh from Dart FFI bindings."
  echo "// Force the linker to pull all Isar Plus FFI entry points from the static archive."
  while IFS= read -r symbol; do
    echo "extern void ${symbol}(void);"
  done < "$symbols_file"
  echo
  echo "typedef void (*IsarPlusForceLinkSymbol)(void);"
  echo
  echo "__attribute__((used))"
  echo "static const IsarPlusForceLinkSymbol isar_plus_force_link_symbols[] = {"
  if [[ -s "$symbols_file" ]]; then
    while IFS= read -r symbol; do
      echo "    (IsarPlusForceLinkSymbol)&${symbol},"
    done < "$symbols_file"
  else
    echo "    NULL,"
  fi
  echo "};"
  echo
  echo "__attribute__((used))"
  echo "void isar_plus_force_link_all_symbols(void) {"
  echo "    (void)isar_plus_force_link_symbols;"
  echo "}"
} > "$tmp_output"

{
  echo "#pragma once"
  echo
  echo "// AUTO-GENERATED FILE. DO NOT EDIT."
  echo "// Generated by tool/generate_force_link_symbols.sh."
  echo
  echo "#ifdef __cplusplus"
  echo "extern \"C\" {"
  echo "#endif"
  echo
  echo "void isar_plus_force_link_all_symbols(void);"
  echo
  echo "#ifdef __cplusplus"
  echo "}"
  echo "#endif"
} > "$tmp_header"

mkdir -p "$(dirname "$OUTPUT_FILE")"
mkdir -p "$(dirname "$HEADER_FILE")"
mv "$tmp_output" "$OUTPUT_FILE"
mv "$tmp_header" "$HEADER_FILE"
echo "Generated $OUTPUT_FILE and $HEADER_FILE with $(wc -l < "$symbols_file" | tr -d ' ') symbols."
